### ISSUE TITLE
Enable zstd support

### ISSUE THREAD

**Issue by nlgranger** [conda-forge/squashfuse-feedstock#2]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Please enable zstd backend, it is already supported by squashfuse and zstd is in the base environment dependencies already.

**Comment by xhochy** [comment]
@nlgranger please provide a PR that enables that.
